name: build_x86_64_latest

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker-image:
    name: Make Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
